---
- name: Run phpmyadmin
  docker_container:
    image: phpmyadmin/phpmyadmin:latest
    name: phpmyadmin
    env:
      PMA_ABSOLUTE_URI: "{{ phpmyadmin_absolute_uri }}"
      PMA_HOSTS: "{{ phpmyadmin_mysql_hosts|join(',') }}"
    labels:
      traefik.backend: phpmyadmin
      traefik.frontend.rule: "{{ phpmyadmin_traefik_frontend_rule }}"
      traefik_network: "{{ phpmyadmin_traefik_network }}"
      traefik.port: "80"
      traefik.priority: "{{ phpmyadmin_traefik_priority }}"
    pull: true
    recreate: true
    restart_policy: always
    state: "{{ phpmyadmin_state }}"

- name: Create network
  docker_network:
    appends: true
    driver: bridge
    name: "{{ item }}"
    connected: phpmyadmin
  with_items: "{{ phpmyadmin_networks }}"
  ignore_errors: yes
